// -------------------------------------------------------------
// 
// File Name: /home/yangli18/Documents/yangzai/PFC/qr_simulink/HDL/qr10/fourxfour_designfxdpt_givens/fourxfour_designfxdpt_tc.v
// Created: 2019-10-01 15:17:02
// 
// Generated by MATLAB 9.5 and HDL Coder 3.13
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: fourxfour_designfxdpt_tc
// Source Path: fourxfour_designfxdpt_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clock_en
// 
// enb_2_1_0   : identical to clock_en
// enb         : 2x slower than clk with last phase
// enb_1_1_1   : 2x slower than clk with phase 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module fourxfour_designfxdpt_tc
          (clk,
           reset,
           clock_en,
           enb_2_1_0,
           enb,
           enb_1_1_1);


  input   clk;
  input   reset;
  input   clock_en;
  output  enb_2_1_0;
  output  enb;
  output  enb_1_1_1;


  reg  count2;
  wire phase_all;
  reg  phase_0;
  wire phase_0_tmp;
  reg  phase_1;
  wire phase_1_tmp;


  always @ (posedge clk)
    begin: Counter2
      if (reset == 1'b1) begin
        count2 <= 1'b1;
      end
      else begin
        if (clock_en == 1'b1) begin
            count2 <= ~ count2;
        end
      end
    end // Counter2

  assign phase_all = clock_en ? 1'b1 : 1'b0;

  always @ ( posedge clk)
    begin: temp_process1
      if (reset == 1'b1) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (clock_en == 1'b1) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end // temp_process1

  assign  phase_0_tmp = (count2 == 1'b1 && clock_en == 1'b1) ? 1'b1 : 1'b0;

  always @ ( posedge clk)
    begin: temp_process2
      if (reset == 1'b1) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (clock_en == 1'b1) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end // temp_process2

  assign  phase_1_tmp = (count2 == 1'b0 && clock_en == 1'b1) ? 1'b1 : 1'b0;

  assign enb_2_1_0 =  phase_all & clock_en;

  assign enb =  phase_0 & clock_en;

  assign enb_1_1_1 =  phase_1 & clock_en;


endmodule  // fourxfour_designfxdpt_tc

